spring:
    datasource:
        url: jdbc:mysql://${DATABASE_HOST}:3306/development
        username: root
        password: password
        driver-class-name: org.mariadb.jdbc.Driver
    sql:
        init:
            mode: always
            schema-locations: classpath:db/initdb/schema.sql
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MariaDB106Dialect
    test:
        database:
            replace: none
mybatis:
    mapper-locations: 
        - classpath:net/banatech/diy_dev_diary/repository/user/mybatis/*.xml
        - classpath:net/banatech/diy_dev_diary/repository/product/mybatis/*.xml
