spring:
    datasource:
        url: jdbc:mysql://${DATABASE_HOST}:3306/development
        username: root
        password: password
        driver-class-name: org.mariadb.jdbc.Driver
    sql:
        init:
            mode: always
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MariaDB106Dialect
    test:
        database:
            replace: none
